language: c

cache:
  directories:
  - $HOME/.ccache
  
addons:
  apt:
    packages:
      - acl
      - attr
      - autoconf
      - bison
      - build-essential
      - ccache
      - curl
      - debhelper
      - dnsutils
      - docbook-xml
      - docbook-xsl
      - emacs24-nox
      - flex
      - gdb
      - git
      - jed
      - krb5-user
      - libacl1-dev
      - libaio-dev
      - libattr1-dev
      - libblkid-dev
      - libbsd-dev
      - libcap-dev
      - libcups2-dev
      - libgnutls-dev
      - libjson-perl
      - libldap2-dev
      - libncurses5-dev
      - libpam0g-dev
      - libparse-yapp-perl
      - libpopt-dev
      - libreadline-dev
      - perl
      - perl-modules
      - pkg-config
      - python-all-dev
      - python-crypto
      - python-dev
      - python-dnspython
      - python-novaclient
      - screen
      - xsltproc
      - zlib1g-dev
install:
 - git fetch --unshallow
 - ./script/autobuild.py --tail --testbase=/tmp --ccache=$HOME/.ccache

